name: Dockerization
on:
  push:
    # paths:
    #   - 'sub-project/**'
    paths-ignore:
      - '**.md'
jobs:
  build:
    name: dockerize
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Print environment
      run: |
        printenv | grep GITHUB_
    - name: Build and publish
      uses: iaean/ci/dockerize@master
      with:
        context: dsc
        github_token: ${{ secrets.GITHUB_TOKEN }}
        docker_token: ${{ secrets.DOCKER_TOKEN }}
    - name: Build and publish
      uses: iaean/ci/dockerize@master
      with:
        context: lb
        image: dsc-proxy
        append-image-suffix: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
        docker_token: ${{ secrets.DOCKER_TOKEN }}

#  publish:
#    name: docker push
#    runs-on: ubuntu-latest
#    steps:
#    - name: Publish docker images
#      run: |
#        docker images
